# Generated by Django 6.0 on 2026-01-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0003_merge_20251230_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='commune',
            field=models.CharField(blank=True, help_text="Commune oÇù l'incident a eu lieu", max_length=100, null=True, verbose_name='Commune'),
        ),
        migrations.AddField(
            model_name='incident',
            name='wilaya',
            field=models.CharField(blank=True, help_text="Wilaya où l'incident a eu lieu", max_length=100, null=True, verbose_name='Wilaya'),
        ),
    ]
