# Generated by Django 6.0 on 2025-12-28 09:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('code_chauffeur', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('num_permis', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Le permis doit contenir exactement 10 chiffres.', regex='^[0-9]{10}$')])),
                ('categorie_permis', models.CharField(choices=[('A', 'Moto (A)'), ('B', 'Voiture (B)'), ('C', 'Camion (C)')], max_length=1)),
                ('statut_dispo', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('code_d', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Algérie', max_length=100)),
                ('zone_geo', models.CharField(choices=[('NORD', 'Nord'), ('SUD', 'Sud'), ('EST', 'Est'), ('OUEST', 'Ouest'), ('CENTRE', 'Centre')], max_length=10, verbose_name='Zone Géographique')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('matricule', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Le matricule doit contenir exactement 6 chiffres.', regex='^[0-9]{6}$')])),
                ('type_vehicule', models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('CAMION', 'Camion')], max_length=10)),
                ('capacite_poids', models.FloatField(verbose_name='Capacité Max Poids (kg)')),
                ('capacite_volume', models.FloatField(verbose_name='Capacité Max Volume (m3)')),
                ('etat', models.CharField(default='Opérationnel', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('code_tarif', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type_service', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('tarif_base_destination', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('numexp', models.AutoField(primary_key=True, serialize=False)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tarification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistique.tarification')),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('code_t', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_tournee', models.DateField()),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.chauffeur')),
                ('expeditions', models.ManyToManyField(blank=True, related_name='tournees', to='logistique.expedition')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.vehicule')),
            ],
        ),
    ]
