# Generated by Django 6.0 on 2026-01-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournee',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('INCIDENT', 'Incident')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='expeditions',
            field=models.ManyToManyField(related_name='tournees', to='logistique.expedition', verbose_name='Colis dans la tournée'),
        ),
    ]
