# Generated by Django 6.0 on 2026-01-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0002_tournee_statut_alter_tournee_expeditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='statut',
            field=models.CharField(default='EN_ATTENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='expeditions',
            field=models.ManyToManyField(related_name='tournees', to='logistique.expedition', verbose_name='Colis'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('AGENT_LOGISTIQUE', 'Agent'), ('ADMIN', 'Admin')], default='AGENT_LOGISTIQUE', max_length=20),
        ),
    ]
