# Generated by Django 6.0 on 2025-12-30 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_initial'),
        ('expeditions', '0002_rename_expedition_code_cl_36b8f4_idx_expedition_code_cl_f99eeb_idx_and_more'),
    ]

    operations = [
    ]
