# Generated by Django 6.0 on 2026-01-03 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0003_merge_20260101_2025'),
        ('expeditions', '0004_incident_commune_incident_wilaya_and_more'),
    ]

    operations = [
    ]
