# Generated by Django 6.0 on 2026-01-11 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('CodeClient', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Adresse', models.TextField()),
                ('Tel', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('CodeRapport', models.AutoField(primary_key=True, serialize=False)),
                ('MotifR', models.TextField()),
                ('Delais', models.IntegerField(help_text='Délai en jours')),
                ('NbrREC', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('CodeHist', models.AutoField(primary_key=True, serialize=False)),
                ('DateAction', models.DateTimeField(auto_now_add=True)),
                ('TypeAction', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('CodeClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('CodeREC', models.AutoField(primary_key=True, serialize=False)),
                ('Nature', models.CharField(max_length=100)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Etat', models.CharField(choices=[('Nouvelle', 'Nouvelle'), ('En cours', 'En cours'), ('Résolue', 'Résolue'), ('Annulée', 'Annulée')], default='Nouvelle', max_length=50)),
                ('CodeClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Contient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeRapport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamations', to='clients.rapport')),
                ('CodeREC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='clients.reclamation')),
            ],
            options={
                'unique_together': {('CodeREC', 'CodeRapport')},
            },
        ),
    ]
