# Generated by Django 6.0 on 2026-01-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reclamation',
            name='Etat',
            field=models.CharField(choices=[('Nouvelle', 'Nouvelle'), ('En cours', 'En cours'), ('Résolue', 'Résolue'), ('Annulée', 'Annulée')], default='Nouvelle', max_length=50),
        ),
    ]
