# Generated by Django 6.0 on 2025-12-29 15:22

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('code_chauffeur', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('num_permis', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Le permis doit contenir exactement 10 chiffres.', regex='^[0-9]{10}$')])),
                ('categorie_permis', models.CharField(choices=[('A', 'Moto (A)'), ('B', 'Voiture (B)'), ('C', 'Camion (C)')], max_length=1)),
                ('statut_dispo', models.BooleanField(default=True, verbose_name='Disponible')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('code_d', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ville', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Algérie', max_length=100)),
                ('zone_geo', models.CharField(choices=[('NORD', 'Nord'), ('SUD', 'Sud'), ('EST', 'Est'), ('OUEST', 'Ouest'), ('CENTRE', 'Centre')], max_length=10, verbose_name='Zone Géographique')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('matricule', models.CharField(max_length=6, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Le matricule doit contenir exactement 6 chiffres.', regex='^[0-9]{6}$')])),
                ('type_vehicule', models.CharField(choices=[('MOTO', 'Moto'), ('VOITURE', 'Voiture'), ('CAMION', 'Camion')], max_length=10)),
                ('capacite_poids', models.FloatField(verbose_name='Capacité Max Poids (kg)')),
                ('capacite_volume', models.FloatField(verbose_name='Capacité Max Volume (m3)')),
                ('etat', models.CharField(default='Opérationnel', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('AGENT_LOGISTIQUE', 'Agent de Transport / Logistique'), ('ADMIN', 'Administrateur')], default='AGENT_LOGISTIQUE', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('code_tarif', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type_service', models.CharField(choices=[('STANDARD', 'Standard'), ('EXPRESS', 'Express'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('tarif_base_destination', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_poids', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarif_volume', models.DecimalField(decimal_places=2, max_digits=10)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('numexp', models.AutoField(primary_key=True, serialize=False)),
                ('poids', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('volume', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('tarification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistique.tarification')),
            ],
        ),
        migrations.CreateModel(
            name='Tournee',
            fields=[
                ('code_t', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('date_tournee', models.DateField()),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.chauffeur')),
                ('expeditions', models.ManyToManyField(blank=True, related_name='tournees', to='logistique.expedition')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistique.vehicule')),
            ],
        ),
    ]
