# Generated by Django 6.0 on 2026-01-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='code_d',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
