# Generated by Django 6.0 on 2026-01-22 13:21

import logistique.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0002_alter_destination_code_d'),
    ]

   # operations = [
       # migrations.AlterModelManagers(
           # name='utilisateur',
            #managers=[
              #  ('objects', logistique.models.UtilisateurManager()),
          #  ],
       # ),
    #]
