# Generated by Django 6.0 on 2026-01-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='statut',
            field=models.CharField(default='EN_ATTENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='tournee',
            name='statut',
            field=models.CharField(choices=[('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('INCIDENT', 'Incident')], default='EN_COURS', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournee',
            name='expeditions',
            field=models.ManyToManyField(related_name='tournees', to='logistique.expedition', verbose_name='Colis'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('AGENT_LOGISTIQUE', 'Agent'), ('ADMIN', 'Admin')], default='AGENT_LOGISTIQUE', max_length=20),
        ),
    ]
