# Generated by Django 6.0 on 2025-12-25 17:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='montant',
        ),
        migrations.AlterField(
            model_name='facture',
            name='ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Montant Hors Taxes (somme des expéditions, calculé automatiquement)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant HT (DA)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Montant Total Toutes Taxes Comprises (HT + TVA, calculé automatiquement)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TTC (DA)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='TVA calculée sur HT (19%, calculé automatiquement)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TVA (DA)'),
        ),
    ]
