# Generated by Django 6.0 on 2025-12-28 16:15

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('facturation', '0002_remove_facture_montant_alter_facture_ht_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='facture',
            new_name='facture_code_cl_6a6f6f_idx',
            old_name='facture_code_cl_34ef0c_idx',
        ),
        migrations.AlterField(
            model_name='facture',
            name='code_client',
            field=models.ForeignKey(blank=True, help_text='Client à qui appartient la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='est_payee',
            field=models.BooleanField(default=False, verbose_name='Payée intégralement'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Montant Hors Taxes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant HT (DA)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Montant Total TTC', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TTC (DA)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='TVA 19%', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TVA (DA)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='montant_verse',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant versé (DA)'),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='remarques',
            field=models.TextField(blank=True, null=True, verbose_name='Remarques'),
        ),
    ]
