# Generated by Django 6.0 on 2025-12-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expeditions', '0002_initial'),
        ('facturation', '0003_rename_facture_code_cl_34ef0c_idx_facture_code_cl_6a6f6f_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='etrefacture',
            constraint=models.UniqueConstraint(fields=('numexp',), name='unique_expedition_facturee'),
        ),
    ]
