# Generated by Django 6.0 on 2026-01-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0004_etrefacture_unique_expedition_facturee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='code_facture',
            field=models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
