# Generated by Django 6.0 on 2026-01-07 15:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturation', '0005_alter_facture_code_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant Hors Taxes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant HT (DA)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant Total TTC', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TTC (DA)'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TVA 19%', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TVA (DA)'),
        ),
    ]
