# Generated by Django 6.0 on 2026-01-11 23:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('code_inc', models.AutoField(primary_key=True, serialize=False, verbose_name='Code incident')),
                ('type', models.CharField(choices=[('RETARD', 'Retard de livraison'), ('PERTE', 'Colis perdu'), ('ENDOMMAGEMENT', 'Colis endommagé'), ('PROBLEME_TECHNIQUE', 'Problème technique'), ('ADRESSE_INCORRECTE', 'Adresse incorrecte'), ('DESTINATAIRE_ABSENT', 'Destinataire absent'), ('REFUS_RECEPTION', 'Refus de réception'), ('ACCIDENT', 'Accident'), ('AUTRE', 'Autre')], max_length=30, verbose_name="Type d'incident")),
                ('commentaire', models.TextField(help_text="Description détaillée de l'incident", verbose_name='Commentaire')),
                ('piece_jointe', models.FileField(blank=True, help_text='Photo ou document justificatif', null=True, upload_to='incidents/%Y/%m/%d/', verbose_name='Pièce jointe')),
                ('etat', models.CharField(choices=[('OUVERT', 'Ouvert'), ('EN_COURS', 'En cours de traitement'), ('RESOLU', 'Résolu'), ('FERME', 'Fermé'), ('ANNULE', 'Annulé')], default='OUVERT', max_length=20, verbose_name='État')),
                ('resolution', models.TextField(blank=True, help_text='Description de la solution apportée', null=True, verbose_name='Résolution')),
                ('wilaya', models.CharField(blank=True, help_text="Wilaya où l'incident a eu lieu", max_length=100, null=True, verbose_name='Wilaya')),
                ('commune', models.CharField(blank=True, help_text="Commune oÇù l'incident a eu lieu", max_length=100, null=True, verbose_name='Commune')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de signalement')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incident',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('numexp', models.AutoField(primary_key=True, serialize=False, verbose_name="Numéro d'expédition")),
                ('poids', models.DecimalField(decimal_places=2, help_text='Poids du colis en kilogrammes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Poids (kg)')),
                ('volume', models.DecimalField(decimal_places=2, help_text='Volume du colis en mètres cubes', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Volume (m³)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_PREPARATION', 'En préparation'), ('EN_TRANSIT', 'En transit'), ('EN_CENTRE_TRI', 'En centre de tri'), ('EN_COURS_LIVRAISON', 'En cours de livraison'), ('LIVRE', 'Livré'), ('ECHEC_LIVRAISON', 'Échec de livraison'), ('RETOUR', "Retourné à l'expéditeur")], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('description', models.TextField(blank=True, help_text='Description détaillée du contenu', null=True, verbose_name='Description du colis')),
                ('montant_estime', models.DecimalField(blank=True, decimal_places=2, help_text='Montant calculé automatiquement', max_digits=10, null=True, verbose_name='Montant estimé (DA)')),
                ('code_client', models.ForeignKey(blank=True, help_text='Client qui envoie le colis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Expédition',
                'verbose_name_plural': 'Expéditions',
                'db_table': 'expedition',
                'ordering': ['-date_creation'],
            },
        ),
    ]
