# Generated by Django 6.0 on 2026-01-11 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expeditions', '0001_initial'),
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='tarification',
            field=models.ForeignKey(blank=True, help_text='Tarif appliqué pour cette expédition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='logistique.tarification', verbose_name='Tarification'),
        ),
        migrations.AddField(
            model_name='incident',
            name='numexp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='expeditions.expedition', verbose_name='Expédition concernée'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['statut'], name='expedition_statut_37e51c_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['code_client'], name='expedition_code_cl_f99eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['date_creation'], name='expedition_date_cr_c84285_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['type'], name='incident_type_2f961b_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['etat'], name='incident_etat_9e38ad_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['numexp'], name='incident_numexp__f78483_idx'),
        ),
    ]
