# Generated by Django 6.0 on 2025-12-28 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('expeditions', '0001_initial'),
        ('logistique', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expedition',
            new_name='expedition_code_cl_f99eeb_idx',
            old_name='expedition_code_cl_36b8f4_idx',
        ),
        migrations.AddField(
            model_name='expedition',
            name='tarification',
            field=models.ForeignKey(blank=True, help_text='Tarif appliqué pour cette expédition', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='logistique.tarification', verbose_name='Tarification'),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='code_client',
            field=models.ForeignKey(blank=True, help_text='Client qui envoie le colis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='clients.client', verbose_name='Client'),
        ),
    ]
