# Generated by Django 6.0 on 2026-01-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('expeditions', '0002_initial'),
        ('logistique', '0003_alter_utilisateur_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='destination',
            field=models.ForeignKey(blank=True, help_text="Destination finale de l'expédition", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='logistique.destination', verbose_name='Destination'),
        ),
        migrations.AddIndex(
            model_name='expedition',
            index=models.Index(fields=['destination'], name='expedition_destina_07f285_idx'),
        ),
    ]
