# Generated by Django 6.0 on 2026-01-11 23:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('expeditions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('code_facture', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('date_f', models.DateField(help_text="Date d'émission de la facture", verbose_name='Date de facturation')),
                ('ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant Hors Taxes', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant HT (DA)')),
                ('tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='TVA 19%', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TVA (DA)')),
                ('ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Montant Total TTC', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant TTC (DA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('est_payee', models.BooleanField(default=False, verbose_name='Payée intégralement')),
                ('code_client', models.ForeignKey(blank=True, help_text='Client à qui appartient la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'facture',
                'ordering': ['-date_f', '-code_facture'],
            },
        ),
        migrations.CreateModel(
            name='EtreFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('numexp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etre_facture_set', to='expeditions.expedition', verbose_name='Expédition')),
                ('code_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions_facturees', to='facturation.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Expédition facturée',
                'verbose_name_plural': 'Expéditions facturées',
                'db_table': 'etre_facture',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('reference_p', models.AutoField(primary_key=True, serialize=False, verbose_name='Référence Paiement')),
                ('date', models.DateField(verbose_name='Date du paiement')),
                ('montant_verse', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant versé (DA)')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('CARTE', 'Carte bancaire'), ('MOBILE', 'Paiement mobile')], default='ESPECES', max_length=20, verbose_name='Mode de paiement')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('remarques', models.TextField(blank=True, null=True, verbose_name='Remarques')),
                ('code_facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='facturation.facture', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiement',
                'ordering': ['-date', '-reference_p'],
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['code_client'], name='facture_code_cl_6a6f6f_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_f'], name='facture_date_f_840750_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['est_payee'], name='facture_est_pay_eab675_idx'),
        ),
        migrations.AddIndex(
            model_name='etrefacture',
            index=models.Index(fields=['numexp'], name='etre_factur_numexp__c9b2bf_idx'),
        ),
        migrations.AddIndex(
            model_name='etrefacture',
            index=models.Index(fields=['code_facture'], name='etre_factur_code_fa_3382ba_idx'),
        ),
        migrations.AddConstraint(
            model_name='etrefacture',
            constraint=models.UniqueConstraint(fields=('numexp',), name='unique_expedition_facturee'),
        ),
        migrations.AlterUniqueTogether(
            name='etrefacture',
            unique_together={('numexp', 'code_facture')},
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['code_facture'], name='paiement_code_fa_7ac6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['date'], name='paiement_date_02b163_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['mode_paiement'], name='paiement_mode_pa_ccaead_idx'),
        ),
    ]
